---
- name: Setup sample bastion host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create Sample ec2 key
      ec2_key:
        name: sample-key
        region: "{{region}}"
      register: key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create sec grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: creating bastion host
      ec2:
        key_name: sample-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: sample
          Owner: Balu
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: sample
          Owner: Balu
          group_id: "{{BastionSG_out.group_id}}"
          vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out

    - name: creating new host
      ec2:
        key_name: sample-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "New_host"
          Project: sample
          Owner: Balu
        exact_count: 1
        count_tag:
          Name: "New_host"
          Project: sample
          Owner: Balu
          group_id: "{{BastionSG_out.group_id}}"
          vpc_subnet_id: "{{privsub1id}}"
      register: new_out
